### ISSUE TITLE
Mbed Studio Support

### ISSUE THREAD

**Issue by oclyke** [sparkfun/mbed-os-ambiq-apollo3#13]
Somehow we got talking about Mbed Studio in a closed issue on the Redboard Artemis Thing Plus...
But user @--idea-list has some useful notes about how to get it started
https://github.com/sparkfun/Artemis_Thing_Plus/issues/3

**Comment by idea--list** [comment]
@oclyke 
Just noticed&tried the arm compiler compatible [branch ](https://github.com/sparkfun/mbed-os-ambiq-apollo3/tree/ambiq-apollo3-armc6-support) of the mbed-os-ambiq-apollo3 repo.

With that branch even code linting seems to work flawless within Mbed Studio while writing mbed-os 6.2.1 code for the Artemis Thing Plus board... I really love it! Now it is time to port my project to this board.

**Comment by idea--list** [comment]
@oclyke 
Discovered&tried the arm compiler compatible [branch ](https://github.com/sparkfun/mbed-os-ambiq-apollo3/tree/ambiq-apollo3-armc6-support)of the repo.

With that branch i can just delete external-tools.json (a file that lets us use GCC as the compiler details are [here](https://os.mbed.com/docs/mbed-studio/current/installing/switching-to-gcc.html)). Code completion and linting works flawless in Mbed Studio with the ARM branch.

The current official blinky [example](https://github.com/ARMmbed/mbed-os-example-blinky) also compiles&runs as expected, however examples of the Serial API found in the [docs](https://os.mbed.com/docs/mbed-os/v6.2/apis/serial-uart-apis.html) of mbed-os V 6.2 throw an assertion error when the board tries to run code compiled with the default ARM compiler shipped with Mbed Studio.

I guess there might be other Mbed APIs that will also need some debugging before we can compile&run them the ARM-way.


All that is great news as of now we can also enjoy linting features of Mbed Studio while writing code in the most recent mbed-os version for Artemis boards. We just need to use the ARM branch while programming and switch to the GCC compiler before generating the .bin file and flashing the board (however this step will reintroduce false errors in linting).

**Comment by idea--list** [comment]
As since Mbed-OS V6.3 the Artemis boards of Sparkfun are officially supported, you just have to update your mbed-os version within Mbed Studio to program these boards within Mbed Studio. This ticket shall be closed for now.
