### ISSUE TITLE
Got stuck trying to upload firmware via USB written in Mbed

### ISSUE THREAD

**Issue by idea--list** [sparkfun/mbed-os-ambiq-apollo3#5]
### Description of defect

Had a conversation back in March [here](https://github.com/sparkfun/Artemis_Thing_Plus/issues/3#issuecomment-647057283).
Meanwhile i was away for some months and also a few things might have been changed since then. 
Basically i am trying to code in Mbed on a Win10 x64 system, compile my .bin file for the Artemis board and finally upload the firmware to the board via USB (as on this board i do not have JTAG connector installed).

#### Target(s) affected by this defect ?
Sparkfun Artemis Thing Plus

#### Toolchain(s) (name and version) displaying this defect ?
GNU Arm Embedded Toolchain 9-2020-q2-update

#### What version of Mbed-os are you using (tag or sha) ?

The ambiq-apollo3-dev branch and ambiq-apollo3-2 branches.

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)
mbed-cli (V1.10.4) manually as described here https://os.mbed.com/docs/mbed-os/v5.15/tools/manual-installation.html

#### How is this defect reproduced ? 
1. Go&grab the latest blinky example for mbed by typing `mbed import mbed-os-example-blinky` in Git-bash.
2. Replace the contents of mbed-os folder of the project with ambiq-apollo3-dev branch or ambiq-apollo3-2 branches (as the example is originally bundled with mbed.os V6.0.0 but that has no clue about the Artemis boards).
3. After that i can successfully compile my .bin file by typing `mbed compile --target SFE_ARTEMIS_THING_PLUS --toolchain GCC_ARM`
4. I can even upload the .bin file by typing `python3 C:/AmbiqSuiteSDK/boards_sfe/common/tools_sfe/ambiq/ambiq_bin2board.py --bin "BUILD/SFE_ARTEMIS_THING_PLUS/GCC_ARM/mbed-os-example-blinky.bin" --load-address-blob 0x20000 --magic-num 0xCB -o "." --version 0x0 --load-address-wired 0x10000 -i 6 --options 0x1 -b 115200 -port "COM4" -r 2 -v`, the process connects to the board, and finally it ends by telling me "Upload complete!"
However the newly uploaded firmware never starts to run on the board even if i try to push the reset button or powercycle the board.

So it seems i fail somehow in the very last step, any help is highly appreciated!

**Comment by idea--list** [comment]
Based on some trial&error/success i found:

I can successfully upload and run any .bin files to my Artemis board that were programmed in AmbiqSDK regardless if i am uploading the .bin file with ambiq secure bootloader or with Sparkfun variable bootloader (by typing `make BOARD=$YOUR_BOARD bootload_asb` or `YOUR_BOARD=artemis_thing_plus` then `make BOARD=$YOUR_BOARD bootload_svl`). Even Artemis Firmware Upload GUI tool works in this case.


However if using Mbed to try programming the Artemis board i can compile the .bin file, even the upload completes successful, but the board never starts running the mbed program.
Based on these findings I **_guess_** Mbed might need a different bootloader than AmbiqSDK uses and this different bootloader for Mbed is still not implemented in ambiq-apollo3-dev and in ambiq-apollo3-2 branches. This might explain why the upload of the mbed .bin succeeds but the MCU can not find the starting address for the Mbed code. But maybe i am wrong with this assumption.

**Comment by idea--list** [comment]
Finally I succeeded programming my Artemis board with Mbed on my win10 x64 computer. Am sooo happy now :-)

1. After having bash, python, GCC, etc installed for a while i just redownloaded&replaced the mbed-os folder of my project with the ambiq-apollo3-dev branch found [here](https://github.com/sparkfun/mbed-os-ambiq-apollo3/tree/ambiq-apollo3-dev).

2. Then i typed these commands in git-bash:
`mbed compile --target SFE_ARTEMIS_THING_PLUS --toolchain GCC_ARM`  (to recompile the program)
`python3 C:/AmbiqSuiteSDK/boards_sfe/common/tools_sfe/ambiq/ambiq_bin2board.py --bin "BUILD/SFE_ARTEMIS_THING_PLUS/GCC_ARM/mbed-os-example-blinky.bin" --load-address-blob 0x20000 --magic-num 0xCB -o "." --version 0x0 --load-address-wired 0xC000 -i 6 --options 0x1 -b 115200 -port "COM4" -r 2 -v`  (to download the .bin file to the board)

I am pretty sure i have tried using for flashing the same options a month ago without success back then, so i think a bug might have been hunted since my last trial 🥇 

Want to emphasize `--load-address-wired 0xC000` is what we need for flashing as with `--load-address-wired 0x10000` the the board just will not start running the program.

**Comment by kerryeven** [comment]
Mbed Studio 1.2.1 Used gui to compile binary then git bash to download bin- works for Edge2, but hard fault for Nano ... just playing around...cool stuff, thx idea--list

**Comment by idea--list** [comment]
@kerryeven 
There is only 1 thing that is even cooler: try replacing the content of the mbed-os folder in your project folder with the [ARMC6 branch](https://github.com/sparkfun/mbed-os-ambiq-apollo3/tree/ambiq-apollo3-armc6-support) that is still under development.

Sparkfun began mbed based development on the GCC_ARM toolchain as that is free. For ARMC6 compiler normally there is a license fee, but in Mbed Studio ARMC6 is the default compiler and in that software it comes free of charge! You can actually let Mbed Studio switch to the GCC_ARM toolchain ([link](https://os.mbed.com/docs/mbed-studio/current/installing/switching-to-gcc.html)) but with that compiler code linting does not work right.

By using the ARMC6 branch of this repo linting works as expected, so i think even Sparkfun will put more emphasis on using the ARMC6 compiler in this project.
